# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d134dc9054b7e160652ee4dbd0db1746d1ebb58d6a3f3035cfc1b5ea1e3b3abcf40a73b9f38f11e95f79f5f5299602fb8f568b29d9bb0913a6ee9f214ffbb1bf

test:
  secret_key_base: c743ee068f02e6750d9a02ca488e19308e72f7c63c017dd9081f3bab70388cc4dfc14bd6ef4adf9fc44bc9cfde223521c7c81b15491c904c8290e546905000fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
